# Generated by Django 3.2.8 on 2021-10-13 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoId', models.TextField()),
                ('content', models.CharField(max_length=150)),
                ('like_counter', models.IntegerField(default=0)),
                ('dislike_counter', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Replies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=150)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtubeclone.comments')),
            ],
        ),
    ]
